import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-waste-hauling-invoice-contract-audit",
  "engine": "recovery",
  "title": "Waste Hauling Invoice & Contract Audit",
  "shortTitle": "Waste Hauling Invoice and Contract Audit",
  "tagline": "Audit waste and recycling invoices against containers, service events, weights, disposal rates, and contract fee terms.",
  "industry": "Waste Services Cost Recovery",
  "buyer": "Multi-site businesses and property portfolios",
  "uiPort": 4718,
  "apiPort": 5718,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Waste Hauling Invoice & Contract Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits in one accountable workflow. Audit waste and recycling invoices against containers, service events, weights, disposal rates, and contract fee terms.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Waste Hauling Invoice & Contract Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("hauling-contract-library","WHI01","Hauling contract library","Execute hauling contract library using hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits.","Produce a governed hauling contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hauler / Service Location","text","Hauler / Service Location · Standard Case"],["caseReference","Hauling contract library Reference","text","WHI01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1538750],["supportedAmount","Evidence-Supported Amount","currency",1292550],["domainDriver","Charge Type","select","Haul",["Haul","Disposal","Contamination"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Hauling contract library case","Location container registry case","Scheduled service calendar case","Service event ingestion case","Missed pickup credit case"]}),
feature("location-container-registry","WHI02","Location container registry","Execute location container registry using hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits.","Produce a governed location container registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hauler / Service Location","text","Hauler / Service Location · Standard Case"],["caseReference","Location container registry Reference","text","WHI02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1538750],["supportedAmount","Evidence-Supported Amount","currency",1292550],["domainDriver","Charge Type","select","Haul",["Haul","Disposal","Contamination"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Hauling contract library case","Location container registry case","Scheduled service calendar case","Service event ingestion case","Missed pickup credit case"]}),
feature("scheduled-service-calendar","WHI03","Scheduled service calendar","Execute scheduled service calendar using hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits.","Produce a governed scheduled service calendar decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hauler / Service Location","text","Hauler / Service Location · Standard Case"],["caseReference","Scheduled service calendar Reference","text","WHI03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1538750],["supportedAmount","Evidence-Supported Amount","currency",1292550],["domainDriver","Charge Type","select","Haul",["Haul","Disposal","Contamination"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Hauling contract library case","Location container registry case","Scheduled service calendar case","Service event ingestion case","Missed pickup credit case"]}),
feature("service-event-ingestion","WHI04","Service event ingestion","Execute service event ingestion using hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits.","Produce a governed service event ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hauler / Service Location","text","Hauler / Service Location · Standard Case"],["caseReference","Service event ingestion Reference","text","WHI04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1538750],["supportedAmount","Evidence-Supported Amount","currency",1292550],["domainDriver","Charge Type","select","Haul",["Haul","Disposal","Contamination"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Hauling contract library case","Location container registry case","Scheduled service calendar case","Service event ingestion case","Missed pickup credit case"]}),
feature("missed-pickup-credit","WHI05","Missed pickup credit","Execute missed pickup credit using hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits.","Produce a governed missed pickup credit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hauler / Service Location","text","Hauler / Service Location · Standard Case"],["caseReference","Missed pickup credit Reference","text","WHI05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1538750],["supportedAmount","Evidence-Supported Amount","currency",1292550],["domainDriver","Charge Type","select","Haul",["Haul","Disposal","Contamination"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Hauling contract library case","Location container registry case","Scheduled service calendar case","Service event ingestion case","Missed pickup credit case"]}),
feature("haul-charge-calculation","WHI06","Haul charge calculation","Execute haul charge calculation using hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits.","Produce a governed haul charge calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hauler / Service Location","text","Hauler / Service Location · Standard Case"],["caseReference","Haul charge calculation Reference","text","WHI06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1538750],["supportedAmount","Evidence-Supported Amount","currency",1292550],["domainDriver","Charge Type","select","Haul",["Haul","Disposal","Contamination"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Hauling contract library case","Location container registry case","Scheduled service calendar case","Service event ingestion case","Missed pickup credit case"]}),
feature("weight-ticket-validation","WHI07","Weight ticket validation","Execute weight ticket validation using hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits.","Produce a governed weight ticket validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hauler / Service Location","text","Hauler / Service Location · Standard Case"],["caseReference","Weight ticket validation Reference","text","WHI07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1538750],["supportedAmount","Evidence-Supported Amount","currency",1292550],["domainDriver","Charge Type","select","Haul",["Haul","Disposal","Contamination"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Hauling contract library case","Location container registry case","Scheduled service calendar case","Service event ingestion case","Missed pickup credit case"]}),
feature("disposal-rate-audit","WHI08","Disposal rate audit","Execute disposal rate audit using hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits.","Produce a governed disposal rate audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hauler / Service Location","text","Hauler / Service Location · Standard Case"],["caseReference","Disposal rate audit Reference","text","WHI08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1538750],["supportedAmount","Evidence-Supported Amount","currency",1292550],["domainDriver","Charge Type","select","Haul",["Haul","Disposal","Contamination"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Hauling contract library case","Location container registry case","Scheduled service calendar case","Service event ingestion case","Missed pickup credit case"]}),
feature("contamination-evidence","WHI09","Contamination evidence","Execute contamination evidence using hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits.","Produce a governed contamination evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hauler / Service Location","text","Hauler / Service Location · Standard Case"],["caseReference","Contamination evidence Reference","text","WHI09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1538750],["supportedAmount","Evidence-Supported Amount","currency",1292550],["domainDriver","Charge Type","select","Haul",["Haul","Disposal","Contamination"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Hauling contract library case","Location container registry case","Scheduled service calendar case","Service event ingestion case","Missed pickup credit case"]}),
feature("fuel-surcharge-validation","WHI10","Fuel surcharge validation","Execute fuel surcharge validation using hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits.","Produce a governed fuel surcharge validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hauler / Service Location","text","Hauler / Service Location · Standard Case"],["caseReference","Fuel surcharge validation Reference","text","WHI10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1538750],["supportedAmount","Evidence-Supported Amount","currency",1292550],["domainDriver","Charge Type","select","Haul",["Haul","Disposal","Contamination"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Hauling contract library case","Location container registry case","Scheduled service calendar case","Service event ingestion case","Missed pickup credit case"]}),
feature("environmental-fee-control","WHI11","Environmental fee control","Execute environmental fee control using hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits.","Produce a governed environmental fee control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hauler / Service Location","text","Hauler / Service Location · Standard Case"],["caseReference","Environmental fee control Reference","text","WHI11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1538750],["supportedAmount","Evidence-Supported Amount","currency",1292550],["domainDriver","Charge Type","select","Haul",["Haul","Disposal","Contamination"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Hauling contract library case","Location container registry case","Scheduled service calendar case","Service event ingestion case","Missed pickup credit case"]}),
feature("invoice-recalculation","WHI12","Invoice recalculation","Execute invoice recalculation using hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits.","Produce a governed invoice recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hauler / Service Location","text","Hauler / Service Location · Standard Case"],["caseReference","Invoice recalculation Reference","text","WHI12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1538750],["supportedAmount","Evidence-Supported Amount","currency",1292550],["domainDriver","Charge Type","select","Haul",["Haul","Disposal","Contamination"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Hauling contract library case","Location container registry case","Scheduled service calendar case","Service event ingestion case","Missed pickup credit case"]}),
feature("hauler-dispute-workflow","WHI13","Hauler dispute workflow","Execute hauler dispute workflow using hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits.","Produce a governed hauler dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hauler / Service Location","text","Hauler / Service Location · Standard Case"],["caseReference","Hauler dispute workflow Reference","text","WHI13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1538750],["supportedAmount","Evidence-Supported Amount","currency",1292550],["domainDriver","Charge Type","select","Haul",["Haul","Disposal","Contamination"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Hauling contract library case","Location container registry case","Scheduled service calendar case","Service event ingestion case","Missed pickup credit case"]}),
feature("credit-reconciliation","WHI14","Credit reconciliation","Execute credit reconciliation using hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits.","Produce a governed credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hauler / Service Location","text","Hauler / Service Location · Standard Case"],["caseReference","Credit reconciliation Reference","text","WHI14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1538750],["supportedAmount","Evidence-Supported Amount","currency",1292550],["domainDriver","Charge Type","select","Haul",["Haul","Disposal","Contamination"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Hauling contract library case","Location container registry case","Scheduled service calendar case","Service event ingestion case","Missed pickup credit case"]}),
feature("location-waste-analytics","WHI15","Location waste analytics","Execute location waste analytics using hauling agreements, containers, service schedules, lifts, weights, disposal tickets, contamination, fuel and environmental fees, invoices, and credits.","Produce a governed location waste analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hauler / Service Location","text","Hauler / Service Location · Standard Case"],["caseReference","Location waste analytics Reference","text","WHI15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1538750],["supportedAmount","Evidence-Supported Amount","currency",1292550],["domainDriver","Charge Type","select","Haul",["Haul","Disposal","Contamination"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Hauling contract library case","Location container registry case","Scheduled service calendar case","Service event ingestion case","Missed pickup credit case"]})
]);
